# Replace this with your own repo whitelist:
orgWhitelist: "github.com/pavan-kumar-99/*"

github:
  user: pavan-kumar-99
  token: ghp_xxxxxxxxx
  secret: 8xxxxxxxxx

repoConfig: |
 ---
  repos:
  - id: /.*/
    branch: /.*/
    workflow: myworkflow
    apply_requirements: [approved, mergeable]
    allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
    allowed_workflows: [myworkflow]
    allow_custom_workflows: true
  workflows:
    myworkflow:
      plan:
        steps:
        - run: echo "In Terraform Init and Plan"
        - init
        - plan:
            extra_args: ["-lock=", "false"]
      apply:
        steps:
        - run: echo "In Terraform Apply"
        - apply

aws:
  credentials: |
    [default]
    aws_access_key_id=Axxx
    aws_secret_access_key=3xxxxxx
    region=ap-south-1

service:
  type: LoadBalancer
  port: 80

podTemplate:
  annotations: {}
  labels: {}

statefulSet:
  annotations: {}
  labels: {}
  securityContext:
    fsGroup: 1000
    runAsUser: 100

ingress:
  enabled: false


resources:
  requests:
    memory: 0.5Gi
    cpu: 100m
  limits:
    memory: 0.5Gi
    cpu: 100m

# Disk space for Atlantis to check out repositories
dataStorage: 5Gi

replicaCount: 1

## test container details
test:
  enabled: true
  image: lachlanevenson/k8s-kubectl
  imageTag: v1.4.8-bash

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
