#The namespace in which all the components should be installed 
namespace: default

#The order in which the Kubernetes resources should be installed 
resources:
- ns.yaml 
- deployment.yaml
- svc.yaml
