apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prom-app
  namespace: default
spec:
  enableAdminAPI: false
  image: quay.io/prometheus/prometheus:v2.28.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: prom
  portName: web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prom
  remoteWrite:
  - url: http://192.168.29.168/api/prom/push
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: prom
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prom
  shards: 1
  version: v2.28.1

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-app
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9092
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prom-app
