apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     {{- include "self-hosted-runner.labels" . | nindent 4 }}
  name: {{ include "self-hosted-runner.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
       {{- include "self-hosted-runner.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "self-hosted-runner.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: github-token
          image: {{ .Values.image.name }}
          envFrom:
            - secretRef:
                name: github-creds
          command:
            - "/bin/sh"
            - "-c"
            - "echo GITHUB_TOKEN=$(curl -s  -X POST -H \"Authorization: token $token\"  -H \"Accept: application/vnd.github.v3+json\"   https://api.github.com/repos/$username/$reponame/actions/runners/registration-token | jq -r .token) > /tmp/token.env"
          volumeMounts:
            - mountPath: /tmp
              name: github-token
      containers:
      - image: {{ .Values.image.name }}
        name: runner
        envFrom:
         - secretRef:
             name: github-creds
        command:
          - "/bin/sh"
          - "-c"
          - "source /tmp/token.env && ./config.sh --url https://github.com/$username/$reponame --token $GITHUB_TOKEN && ./run.sh"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","source /tmp/token.env && ./config.sh remove --token $GITHUB_TOKEN"]
        volumeMounts:
          - mountPath: /tmp
            name: github-token
        resources: 
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
      volumes:
        - name: github-token
          emptyDir: {} 
status: {}
